---
deployment:
  tasks:
    - source /home/lmp723c7ts05/virtualenv/rbscience/3.7/bin/activate && cd /home/lmp723c7ts05/rbscience
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate
    - touch tmp/restart.txt